name: libneo build macos
on:
  push

jobs:
  macos:
    strategy:
      max-parallel: 1
      matrix:
        boost_version: [1.81.0]
    uses: neotene/ci/.github/workflows/build_macos.yml@main
    with:
      boost_version: ${{ matrix.boost_version }}
      boost: false
