name: libneo build windows
on:
  push

jobs:
  windows:
    strategy:
      max-parallel: 1
      matrix:
        boost_version: [1.81.0]
    uses: neotene/ci/.github/workflows/build_windows.yml@main
    with:
      boost_version: ${{ matrix.boost_version }}
      boost: false
