name: libneo test macos

on:
  workflow_run:
    workflows: ["libneo build macos"]
    types:
      - completed

jobs:
  macos-lastest:
    runs-on: macos-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cached build directory
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            build
          key: build-macos
          restore-keys: |
            build-macos

      - if: steps.restore-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Meson test
        if: steps.restore-cache.outputs.cache-hit == 'true'
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: -v
          meson-version: 1.1.0
